FROM node:lts-alpine3.19 AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
RUN npm install react-router-dom
RUN npm install jwt-decode
COPY src /app/src
COPY public /app/public
RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]