#FROM node:lts-alpine3.19
#
#EXPOSE 3000
#
#WORKDIR /app
#
#COPY ./package.json .
#COPY ./package-lock.json .
#COPY ./src/ ./src
#COPY ./public/ ./public
#
#RUN npm install --silent
#
#CMD ["npm", "start"]

FROM node:lts-alpine3.19 AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY src /app/src
COPY public /app/public

RUN npm run build


FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]