version: "3.8"

services:
#  lernenwor:
#    build: .
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      maindb:
#        condition: service_healthy

  maindb:
    image: postgres:alpine3.19
    restart: always
    user: postgres
    environment:
#      POSTGRES_USER: user
#      PGUSER: user
      POSTGRES_PASSWORD: user1234
      POSTGRES_DB: central
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 10s
      start_interval: 5s
      interval: 20s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer
    restart: always
    ports:
      - "5000:8080"
    depends_on:
      maindb:
        condition: service_healthy