version: "3.8"

services:
  frontend:
    image: prozet/frontend:${GIT_COMMIT}
    ports:
      - "80:80"
    depends_on:
      - lernenwor

  lernenwor:
    image: prozet/lernenwor:${GIT_COMMIT}
    secrets:
      - postgres_password
      - postgres_user
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    depends_on:
      - maindb
#      - pgadmin

  maindb:
    image: postgres:alpine3.19
    secrets:
      - postgres_password
      - postgres_user
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: central
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256 --auth-local=scram-sha-256'
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 10s
      interval: 20s
      timeout: 10s
      retries: 3
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-abcd-xyz@list.ru}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8888:80"
    depends_on:
      - maindb
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
#      start_period: 10s
#      interval: 20s
#      timeout: 10s
#      retries: 3
    volumes:
      - pgadmin:/var/lib/pgadmin

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true

volumes:
  postgres:
  pgadmin: