version: "3.8"

services:
  frontend:
    image: prozet/frontend:${GIT_COMMIT}
    ports:
      - "80:80"
    depends_on:
      - lernenwor

  lernenwor:
    image: prozet/lernenwor:${GIT_COMMIT}
    secrets:
      - postgres_password
      - postgres_user
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        export POSTGRES_USER=$(cat /run/secrets/postgres_user)
        export POSTGRES_PASSWORD=$(cat /run/secrets/postgres_password)
        java -jar /app/app.jar --spring.profiles.active=prod
    depends_on:
      maindb:
        condition: service_healthy
      pgadmin:
        condition: service_started

  maindb:
    image: postgres:alpine3.19
    secrets:
      - postgres_password
      - postgres_user
    entrypoint: [ "sh", "-c" ]
    command:
      - |
        export POSTGRES_USER=$(cat /run/secrets/postgres_user)
        export POSTGRES_PASSWORD=$(cat /run/secrets/postgres_password)
        docker-entrypoint.sh postgres
    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: user1234
      POSTGRES_DB: central
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256 --auth-local=scram-sha-256'
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 10s
      interval: 20s
      timeout: 10s
      retries: 3
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-abcd-xyz@list.ru}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8888:80"
    depends_on:
      maindb:
        condition: service_healthy
    volumes:
      - pgadmin:/var/lib/pgadmin

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true

volumes:
  postgres:
  pgadmin: