server:
  port: 8080

spring:
  application:
    name: lernenwor
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop