server:
  port: 8080

spring:
  application:
    name: lernenwor
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    servlet:
      path: /api
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: "jdbc:postgresql://maindb:5432/central"
    driver-class-name: org.postgresql.Driver