spring:
  datasource:
#    name: ""
#    password: ""
#    url: "jdbc:h2:./lernenwor"
    name: postgres
    password: user1234
    url: "jdbc:postgresql://maindb:5432"
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yml