server:
  port: 8080

spring:
  application:
    name: lernenwor
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    servlet:
      path: /api
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: user1234
#    url: "jdbc:postgresql://localhost:5432/central"
    driver-class-name: org.postgresql.Driver