spring:
  datasource:
#    name: ""
#    password: ""
#    url: "jdbc:h2:./lernenwor"
    name: postgres
    password: user1234
    url: "jdbc:postgresql://localhost:5432/central"
    driver-class-name: org.postgresql.Driver
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yml