#spring:
#  datasource:
#    name: user
#    password: user1234
#    url: "jdbc:postgresql://database:5432/shopme"
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        dialect: spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL81Dialect
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yml